site_name: Birch
site_url: https://birch-lang.org
site_description: 'Birch is an open source probabilistic programming language that transpiles to C++. It features automatic differentiation, automatic marginalization, and automatic conditioning.'
repo_url: https://github.com/lawmurray/Birch
repo_name: lawmurray/Birch
edit_uri: ""
theme:
  name: material
  custom_dir: material
  favicon: fontawesome/solid/leaf
  icon:
    logo: fontawesome/solid/leaf
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: white
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.footer
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - markdown.extensions.smarty
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: markdeep
          class: markdeep
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - /js/settings.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://morgan3d.github.io/markdeep/latest/markdeep.min.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lawmurray
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@lawmurray
nav:
  - index.md
  - 'Getting Started':
    - getting-started/index.md
    - getting-started/hello-world.md
    - getting-started/linear-regression.md
    - getting-started/markov-model.md
    - getting-started/next-steps.md
  - 'Key Concepts':
    - concepts/index.md
    - concepts/distributions.md
    - concepts/randoms.md
    - concepts/expressions.md
    - concepts/models.md
    - concepts/graphical-models.md
    - concepts/programmatic-models.md
    - concepts/automatic-differentiation.md
    - concepts/automatic-marginalization.md
    - concepts/automatic-conditioning.md
    - concepts/delayed-sampling.md
    - concepts/probabilistic-inference.md
    - concepts/summary.md
  - 'The Language':
    - language/index.md
    - language/variables.md
    - language/types.md
    - language/assignments.md
    - language/control_flow.md
    - language/assertions.md
    - language/arrays.md
    - language/optionals.md
    - language/tuples.md
    - language/functions.md
    - language/lambdas.md
    - language/programs.md
    - language/operators.md
    - language/classes.md
    - language/aliases.md
    - language/casts.md
    - language/probability.md
  - 'Reference Docs':
    - 'docs.birch-lang.org': 'https://docs.birch-lang.org'
  - 'Getting Involved':
    - getting-involved/index.md
  - about.md
  
