site_name: Birch
site_description: 'Birch is an open source probabilistic programming language, based on imperative and object-oriented paradigms. It provides the trio of automatic differentiation, automatic marginalization, and automatic conjugacy, combined in an inference engine in the framework of Sequential Monte Carlo (SMC).'
repo_url: https://github.com/lawmurray/Birch
repo_name: lawmurray/Birch
edit_uri: ""
theme:
  name: material
  custom_dir: material
  favicon: fontawesome/solid/leaf
  icon:
    logo: fontawesome/solid/leaf
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: white
    accent: deep orange
  features:
    - tabs
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - markdown.extensions.smarty
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: markdeep
          class: markdeep
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - /js/markdeep.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://morgan3d.github.io/markdeep/latest/markdeep.min.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lawmurray
google_analytics:
  - 'UA-115470196-1'
  - 'auto'
nav:
  - index.md
  - 'Getting Started':
    - getting-started/index.md
    - getting-started/hello-world.md
    - getting-started/linear-regression.md
    - getting-started/markov-model.md
    - getting-started/next-steps.md
  - 'Concepts':
    - concepts/index.md
    - concepts/distributions.md
    - concepts/randoms.md
    - concepts/models.md
    - concepts/graphical-models.md
    - concepts/programmatic-models.md
    - concepts/expressions.md
    - concepts/automatic-differentiation.md
    - concepts/automatic-marginalization.md
    - concepts/automatic-conditioning.md
    - concepts/delayed-sampling.md
    - concepts/probabilistic-inference.md
    - concepts/summary.md
  - 'Language':
    - language/index.md
    - language/variables.md
    - language/types.md
    - language/assignments.md
    - language/control_flow.md
    - language/assertions.md
    - language/arrays.md
    - language/optionals.md
    - language/tuples.md
    - language/functions.md
    - language/lambdas.md
    - language/programs.md
    - language/operators.md
    - language/classes.md
    - language/aliases.md
    - language/casts.md
    - language/probability.md
  - 'Reference':
    - 'docs.birch.sh': 'https://docs.birch.sh'
  - about.md
